name: pp_tool
description: Automatically and quickly generate custom templates for Flutter projects.
version: 1.0.4
repository: https://github.com/xiaopindev/pp_tool

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  ptool: pp_tool

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.6.0
  archive: ^3.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
